### ISSUE TITLE
Visibility slider

### ISSUE THREAD

**Issue by ykeara** [ykeara/OpenVR-AdvancedSettings#3]
Visibility @ 0 percent is still ~ 30 percent.

Thinking of two solutions

1. change display to reflect minimum is still ~30%
2. see if possible to actually fix.

**Comment by gr3y5had0w** [comment]
Please "2. see if possible to actually fix." ✌️ It's really annoying in Standing-only-mode, because it's always there and visible. Would be nice to reduce the visibility lower than 30%, so it's not so intrusive.

**Comment by ykeara** [comment]
Setting the fade distance to 0 will disable chaperone currently, I have glanced at it, and this is probably the solution moving forward. ( I may add a button to "disable" but it will simply set fade to 0)

The main Repo is now @ https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings as soon as I get my stuff finished there will be a release there to bring it up further than my last release, and   all further development will be probably done under that org. WE have currently been doing some major code re-factoring and org work to get all the developers currently working on it on the same page

**Comment by gr3y5had0w** [comment]
Actually setting the fade distance to 0 does not disable the ring in standing-only-mode. It only works with roomscale chaperone.

**Comment by ykeara** [comment]
Hmm, I will look into it, I would still recommend if you play with chaperone off that you should set up "room-scale" even if just doing standing. Quick glance nothing in the Advanced settings code limiting the standing/roomscale setup so I am assuming it has something to do with openvr/steamvr directly.

Certainly I will keep it as a bug and open open.

**Comment by ykeara** [comment]
Fixed in 2.8.0 see https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings
