### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by mamefan** [ykeara/OpenVR-AdvancedSettings#5]
I installed it, and there's no advanced settings circle. I uninstalled the old openvr advanced settings before installing this.

**Comment by mamefan** [comment]
Did not delete old app folder. Will try.

**Comment by ykeara** [comment]
navigate to the install directory (C:\Program Files\OpenVR-AdvancedSettings) and run advancedsettings.exe inside of it (preferably as admin though it shouldn't matter). Possible That it has not registered correctly to automatically launch with steamVR (should only have to do it once if this is the case.

**Comment by mamefan** [comment]
Deleting the old advanced settings folder fixed it

**Comment by ykeara** [comment]
Alright Awesome, going to close issue out.
